# NEURAL NETWORKS

# Implementation of OR GATE

In [1]:
import numpy as np # to get numpy function 

Input values:

In [2]:
# Assign Input values:
feature_set = np.array([[0,0],[0,1],[1,0],[1,1]])
print(feature_set.shape)
feature_set

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

Target Output

In [3]:
# Target Output:
target_output = np.array([[0,1,1,1]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [1],
       [1],
       [1]])

In [4]:
# Assign the weights

weights=np.array([[0.1],[0.2]])
print(weights.shape) # Printing shape of Weights
weights # printing Weights

(2, 1)


array([[0.1],
       [0.2]])

In [5]:
# Adding Bias Values and Assigning a Learning Rate :

#bias weight
bias=0.3

# Learning Rate
lr=0.05

In [6]:
#Applying a Sigmoid Function:

def sigmoid(x):
    return 1/(1+np.exp(-x))

In [7]:
# Derivative of sigmoid function:

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [8]:
# epoch is simply iterations 
# The main logic for predicting output and updating the weight values:

for epoch in range(10000):
    inputs = feature_set

    # feedforward input
    in_o = np.dot(feature_set, weights) + bias

    #feedforward output
    out_o = sigmoid(in_o)


    # backpropagation calculating error
    error = out_o - target_output

    # applying formula
    print(error.sum())

    # Calculating derivative
    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    # Multiplying individual derivatives
    deriv = derror_douto * douto_dino

    # Multiplying with the 3rd individual derivative
    # finding the transpose of input features
    inputs = feature_set.T
    deriv_final=np.dot(inputs, deriv)
    
    #updating the weight values
    weights -= lr * deriv_final

    # updating the bias weight value
    for i in deriv:
        bias -= lr * i

-0.558754185648239
-0.5449723292898769
-0.5315134542854335
-0.5183693277777114
-0.5055318634543028
-0.49299312894046377
-0.4807453517449485
-0.46878092391163273
-0.45709240551747266
-0.4456725271456442
-0.4345141914516083
-0.4236104739294215
-0.4129546229758403
-0.4025400593406463
-0.39236037504318566
-0.3824093318272902
-0.3726808592195393
-0.36316905224921825
-0.3538681688822485
-0.34477262721583557
-0.33587700247552477
-0.32717602385175093
-0.3186645712088134
-0.31033767169540705
-0.3021904962824402
-0.2942183562507701
-0.28641669964871663
-0.2787811077367093
-0.271307291434174
-0.2639910877817563
-0.25682845643017205
-0.24981547616536803
-0.24294834147823285
-0.23622335918582282
-0.22963694510992905
-0.22318562081779836
-0.2168660104289325
-0.2106748374910945
-0.204608921927958
-0.19866517706022102
-0.19284060670146874
-0.18713230232960276
-0.18153744033423935
-0.17605327934012704
-0.17067715760633084
-0.16540649050065304
-0.16023876804855286
-0.15517155255561432
-0.150202476302467

In [9]:
# Pritng Weights and bias
print(weights)
print(bias)

[[7.00922425]
 [7.00953281]]
[-3.14905135]


In [10]:
# Predictiong for (0,0)

#taking input
pt=np.array([0,0])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.04112867]


In [11]:
# Predictiong for (0,1)

#taking input
pt=np.array([0,1])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.97937643]


In [12]:
# Predictiong for (1,0)

#taking input
pt=np.array([1,0])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.9793702]


In [13]:
# Predictiong for (1,1)

#taking input
pt=np.array([1,1])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.99998097]


# Implementation of AND GATE

In [14]:
# Assign Input values:

feature_set = np.array([[0,0],[0,1],[1,0],[1,1]])
print(feature_set.shape)
feature_set

(4, 2)


array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [15]:
# Target Output
target_output = np.array([[0,0,0,1]])
target_output = target_output.reshape(4,1)
print(target_output.shape)
target_output

(4, 1)


array([[0],
       [0],
       [0],
       [1]])

In [16]:
# Assign the weights

weights=np.array([[0.24],[0.34]])
print(weights.shape) # Printing shape of Weights
weights # Printing Weights

(2, 1)


array([[0.24],
       [0.34]])

In [17]:
# Adding Bias Values and Assigning a Learning Rate :

#bias weight
bias=0.3

# Learning Rate
lr=0.05

In [18]:
#Applying a Sigmoid Function:

def sigmoid(x):
    return 1/(1+np.exp(-x))

In [19]:
# Derivative of sigmoid function:

def sigmoid_der(x):
    return sigmoid(x)*(1-sigmoid(x))

In [20]:
# epoch is simply iterations 
# The main logic for predicting output and updating the weight values:

for epoch in range(10000):
    inputs = feature_set

    # feedforward input
    in_o = np.dot(feature_set, weights) + bias

    #feedforward output
    out_o = sigmoid(in_o)


    # backpropagation calculating error
    error = out_o - target_output

    # applying formula
    print(error.sum())

    # Calculating derivative
    derror_douto = error
    douto_dino = sigmoid_der(out_o)

    # Multiplying individual derivatives
    deriv = derror_douto * douto_dino

    # Multiplying with the 3rd individual derivative
    # finding the transpose of input features
    inputs = feature_set.T
    deriv_final=np.dot(inputs, deriv)
    
    #updating the weight values
    weights -= lr * deriv_final

    # updating the bias weight value
    for i in deriv:
        bias -= lr * i


1.5678306162476479
1.5479581484211824
1.5282395213010798
1.5086827563746052
1.4892954158216452
1.4700845995096181
1.4510569441337458
1.432218624386293
1.4135753560284665
1.395132400730927
1.3768945725432489
1.3588662458490486
1.3410513646617719
1.3234534531161126
1.306075627011605
1.2889206062678729
1.2719907281551754
1.2552879611690928
1.238813919424234
1.2225698774486033
1.2065567852675227
1.1907752836736623
1.175225719587622
1.1599081614215156
1.1448224143660253
1.1299680355293202
1.1153443488639887
1.1009504598256319
1.0867852697139884
1.0728474896543152
1.059135654183225
1.0456481344092674
1.0323831507241783
1.0193387850459557
1.0065129925797094
0.9939036130865836
0.9815083816550102
0.969324938972081
0.957350841095982
0.9455835687332094
0.934020536026728
0.9226590988633212
0.9114965627102031
0.9005301899924567
0.8897572070241421
0.8791748105069253
0.8687801736108913
0.8585704516528206
0.8485427873876381
0.8386943159290398
0.8290221693154362
0.8195234807373929
0.810195388442658
0.8

In [21]:
# printing Weights and Bias 
print(weights)
print(bias)

[[5.82804756]
 [5.82805018]]
[-9.03058129]


In [22]:
# Predictiong for (0,0)

#taking input
pt=np.array([0,0])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.00011968]


In [23]:
# Predictiong for (0,1)

#taking input
pt=np.array([0,1])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.03907058]


In [24]:
# Predictiong for (1,0)

#taking input
pt=np.array([1,0])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.03907049]


In [25]:
# Predictiong for (1,1)

#taking input
pt=np.array([1,1])

# 1st step
result1= np.dot(pt,weights)+bias

# 2nd step
result2=sigmoid(result1)
    
#print result
print(result2)

[0.93248583]
